version: '2'
services:
  api:
    container_name: api
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - "80:80"
    environment:
      - POSTGRES_PASSWORD=test
      - SETTINGS=.env
    restart: always
